services:
  app:
    build: .
    stdin_open: true
    tty: true
    depends_on:
      - db
  
  db:
    image: redis:alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

volumes:
  redis_data: